stages:
  prepare:
    cmd: python scripts/prepare.py
    deps:
      - data/MachineLearningRating_v3.txt
    outs:
      - data/MachineLearningRating_v3.txt.dvc
    params:
      - columns_to_drop
      - imputation_strategy